#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

# Block commit branch main and branch dev
# branch="$(git rev-parse --abbrev-ref HEAD)"

# if [ "$branch" = "dev" ]; then
#   echo "Dev Branch commit is blocked"
#   exit 1
# fi

# if [ "$branch" = "develop" ]; then
#   echo "Develop Branch commit is blocked"
#   exit 1
# fi

# if [ "$branch" = "master" ]; then
#   echo "Master Branch commit is blocked"
#   exit 1
# fi


# if [ "$branch" = "main" ]; then
#   echo "Main Branch commit is blocked"
#   exit 1
# fi


npm run precommit

